name := "sbtProject"
version := "0.1.0"
scalaVersion := "2.11.8"
libraryDependencies += "org.codehaus.jackson" % "jackson-core-asl" % "1.6.1"
libraryDependencies += "org.scalatest" % "scalatest_2.11" % "3.0.1" % "test"